### PR TITLE
[#22] fix(sensor-demo): correct app IDs and improve script consistency

### LINKED ISSUE #22: [BUG] Incorrect App IDs in Sensor Diagnostics Demo Scripts
## Description

The sensor diagnostics demo scripts were using incorrect app IDs with underscores (`_`) instead of dashes (`-`), causing API calls to fail with "entity not found" errors.

## Root Cause

Mismatch between ROS 2 node naming convention and Gateway API entity ID format:
- **ROS 2 node names** use underscores: `/sensors/lidar_sim`, `/sensors/imu_sim`
- **Gateway API app IDs** use dashes: `lidar-sim`, `imu-sim`, `gps-sim`, `camera-sim`, `anomaly-detector`, `diagnostic-bridge`

All demo scripts were incorrectly using underscore-based IDs when calling the API.

## Steps to Reproduce

1. Start sensor diagnostics demo:
   ```bash
   cd demos/sensor_diagnostics
   docker compose up -d
   ```

2. Run check-demo.sh or any inject script:
   ```bash
   ./check-demo.sh
   ```

3. Observe errors:
   ```
   === 8. Listing LiDAR Configurations ===
   jq: error (at <stdin>:6): Cannot iterate over null (null)
   ```

4. Check API response:
   ```bash
   curl http://localhost:8080/api/v1/apps/lidar_sim/configurations
   # Returns: {"error_code": "entity-not-found", "message": "Entity not found"}
   ```

## Expected vs Actual Behavior

**Expected:**
- Scripts should use correct app IDs with dashes
- API calls should succeed and return data
- No jq parsing errors

**Actual:**
- Scripts used underscore-based IDs
- API returned "entity not found" errors
- jq failed to parse null responses

## Impact

- `check-demo.sh` - Failed at step 8 (configurations) with jq error
- `inject-*.sh` - All fault injection scripts failed silently
- `restore-normal.sh` - Failed to reset configurations and clear faults
- Demo appeared non-functional to users

### Scripts with incorrect IDs:
1. `check-demo.sh` - API demonstration
2. `inject-drift.sh` - Fault injection
3. `inject-noise.sh` - Fault injection
4. `inject-nan.sh` - Fault injection
5. `inject-failure.sh` - Fault injection
6. `restore-normal.sh` - Parameter reset and fault clearing
7. `README.md` - API usage examples

### Incorrect app IDs found:
- ❌ `lidar_sim` → ✅ `lidar-sim`
- ❌ `imu_sim` → ✅ `imu-sim`
- ❌ `gps_sim` → ✅ `gps-sim`
- ❌ `camera_sim` → ✅ `camera-sim`
- ❌ `anomaly_detector` → ✅ `anomaly-detector`
- ❌ `diagnostic_bridge` → ✅ `diagnostic-bridge`

## Environment

-- **OS**: ubuntu 24.04 (Docker)
- **Demo:** sensor_diagnostics (main branch)
- **ROS 2 Distro:** Jazzy

### PR DESCRIPTION
**Pull request by bburda**
## Description

- Fix incorrect app IDs: use dashes instead of underscores
  - lidar_sim -> lidar-sim
  - imu_sim -> imu-sim
  - gps_sim -> gps-sim
  - camera_sim -> camera-sim
  - anomaly_detector -> anomaly-detector
  - diagnostic_bridge -> diagnostic-bridge

- Split run-demo.sh into separate concerns
  - run-demo.sh: only starts Docker services
  - check-demo.sh: new interactive API demonstration script
  - stop-demo.sh: new script to stop services

- Update all scripts to use correct Gateway API entity IDs
  - check-demo.sh: fixed all API endpoint calls
  - inject-*.sh: updated fault injection scripts
  - restore-normal.sh: fixed configuration and fault clearing

- Update documentation
  - README.md: updated Quick Start and API examples
  - demos/sensor_diagnostics/README.md: corrected all API examples

Fixes API calls that were failing with 'entity not found' errors. Makes demo scripts consistent with turtlebot3_integration behavior.

## Related Issue

closes #22 

## Checklist

- [x] Tested locally
- [x] README updated (if needed)

### CODE REVIEW

File: demos/sensor_diagnostics/inject-nan.sh [hunk 1]
```diff
@@ -9,31 +9,31 @@ echo ""
...
+curl -s -X PUT "${API_BASE}/apps/lidar-sim/configurations/inject_nan" \
   -H "Content-Type: application/json" \
   -d '{"value": true}'
 echo ""
 
 # MODERN PATH: IMU/GPS → anomaly_detector → FaultManager (direct service call)
 echo "[MODERN PATH] Enabling IMU inject_nan..."
-echo "  Fault path: imu_sim → anomaly_detector → /fault_manager/report_fault"
-curl -s -X PUT "${API_BASE}/apps/imu_sim/configurations/inject_nan" \
+echo "  Fault path: imu-sim → anomaly_detector → /fault_manager/report_fault"
```
Comment (mfaferek93) [inline demos/sensor_diagnostics/inject-nan.sh]:
```suggestion
echo "  Fault path: imu-sim → anomaly-detector → /fault_manager/report_fault"
```

File: demos/sensor_diagnostics/inject-drift.sh
Comment (mfaferek93) [inline demos/sensor_diagnostics/inject-drift.sh]:
```suggestion
echo "Injecting DRIFT fault (Legacy path: LiDAR → diagnostic-bridge)..."
```

File: demos/sensor_diagnostics/inject-noise.sh
Comment (mfaferek93) [inline demos/sensor_diagnostics/inject-noise.sh]:
```suggestion
# LiDAR/Camera → DiagnosticArray → /diagnostics → diagnostic-bridge → FaultManager
```

Comment (mfaferek93) [inline demos/sensor_diagnostics/inject-noise.sh]:
```suggestion
echo "Injecting HIGH NOISE fault (Legacy path: LiDAR/Camera → diagnostic-bridge)..."
```

Comment (bburda) [reply demos/sensor_diagnostics/inject-noise.sh]: Applied.

File: demos/sensor_diagnostics/inject-drift.sh
Comment (bburda) [reply demos/sensor_diagnostics/inject-drift.sh]: Applied.

[the remark this answers is not in the document]
Comment (bburda) [reply demos/sensor_diagnostics/inject-drift.sh]: Applied.

File: demos/sensor_diagnostics/inject-failure.sh
[the remark this answers is not in the document]
Comment (bburda) [reply demos/sensor_diagnostics/inject-failure.sh]: Applied.

File: demos/sensor_diagnostics/inject-nan.sh [hunk 2]
```diff
@@ -9,31 +9,31 @@ echo ""
...
+curl -s -X PUT "${API_BASE}/apps/imu-sim/configurations/inject_nan" \
   -H "Content-Type: application/json" \
   -d '{"value": true}'
 echo ""
 
 echo "[MODERN PATH] Enabling GPS inject_nan..."
-echo "  Fault path: gps_sim → anomaly_detector → /fault_manager/report_fault"
-curl -s -X PUT "${API_BASE}/apps/gps_sim/configurations/inject_nan" \
+echo "  Fault path: gps-sim → anomaly_detector → /fault_manager/report_fault"
```
[the remark this answers is not in the document]
Comment (bburda) [reply demos/sensor_diagnostics/inject-nan.sh]: Applied.

File: demos/sensor_diagnostics/inject-nan.sh [hunk 3]
```diff
@@ -9,31 +9,31 @@ echo ""
...
 echo "[LEGACY PATH] Enabling LiDAR inject_nan..."
-echo "  Fault path: lidar_sim → /diagnostics topic → diagnostic_bridge → FaultManager"
-curl -s -X PUT "${API_BASE}/apps/lidar_sim/configurations/inject_nan" \
+echo "  Fault path: lidar-sim → /diagnostics topic → diagnostic-bridge → FaultManager"
+curl -s -X PUT "${API_BASE}/apps/lidar-sim/configurations/inject_nan" \
   -H "Content-Type: application/json" \
   -d '{"value": true}'
 echo ""
 
 # MODERN PATH: IMU/GPS → anomaly_detector → FaultManager (direct service call)
```
[the remark this answers is not in the document]
Comment (bburda) [reply demos/sensor_diagnostics/inject-nan.sh]: Applied.

**Review by mfaferek93 — APPROVED** [review]
